spring:
  application:
    name: blog-service

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:blog
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

feign:
  autoconfiguration:
    jackson:
      enabled: true

api:
  kakao:
    token: KakaoAK 7eff070894cdffd690c14c851e2e23ee
  naver:
    client:
      id: noK72Z9zRlNRMzAsmYy8
      secret: ZB36YxIzl2
